language: node_js 
node_js:
 - 14.12.0

before_install:
 - npm install -g codecov
 - python -m pip install --upgrade pip
install:
 - pip install coverage
 - pip install pytest-cov pytest

script:
 - codecov -t 'b1d01bc5-f6df-4594-b982-fca1e29dddd8'


after_success:
 - bash <(curl -s https://codecov.io/bash)